/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * @nullable
 */
export type GetAuthStatus200User = {
  id: string;
  workosUserId: string;
  email: string;
  createdAt: string;
  updatedAt: string;
} | null;

export type GetAuthStatus200 = {
  /** @nullable */
  user: GetAuthStatus200User;
};

export type GetAuthStatus401 = {
  error: string;
};

export const getAuthStatus = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetAuthStatus200>> => {
    return axios.get(
      `/auth/status`,options
    );
  }

export type GetAuthStatusResult = AxiosResponse<GetAuthStatus200>
