/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetTokenUsageSummary200,
  GetTokenUsageSummary401,
  GetTokenUsageSummary500
} from '.././models';

import { customInstance } from '../../custom-client';

export type getTokenUsageSummaryResponse200 = {
  data: GetTokenUsageSummary200
  status: 200
}

export type getTokenUsageSummaryResponse401 = {
  data: GetTokenUsageSummary401
  status: 401
}

export type getTokenUsageSummaryResponse500 = {
  data: GetTokenUsageSummary500
  status: 500
}
    
export type getTokenUsageSummaryResponseSuccess = (getTokenUsageSummaryResponse200) & {
  headers: Headers;
};
export type getTokenUsageSummaryResponseError = (getTokenUsageSummaryResponse401 | getTokenUsageSummaryResponse500) & {
  headers: Headers;
};

export type getTokenUsageSummaryResponse = (getTokenUsageSummaryResponseSuccess | getTokenUsageSummaryResponseError)

export const getGetTokenUsageSummaryUrl = () => {


  

  return `/token-usage/summary`
}

export const getTokenUsageSummary = async ( options?: RequestInit): Promise<getTokenUsageSummaryResponse> => {
  
  return customInstance<getTokenUsageSummaryResponse>(getGetTokenUsageSummaryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


