/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteGmailAccounts200,
  DeleteGmailAccounts401,
  DeleteGmailAccounts404,
  DeleteGmailAccounts500,
  DeleteGmailAccountsParams,
  DeleteTelegram200,
  DeleteTelegram401,
  DeleteTelegram404,
  DeleteTelegram500,
  GetAuthGoogle401,
  GetAuthStatus200,
  GetAuthStatus401,
  GetGmailAccounts200Item,
  GetGmailAccounts401,
  GetGmailAccounts500,
  GetMessages200,
  GetMessages400,
  GetMessages401,
  GetMessages500,
  GetMessagesParams,
  GetNatieMessages200,
  GetNatieMessages401,
  GetNatieMessages500,
  GetOauthGoogleCallback401,
  GetOauthGoogleCallbackParams,
  GetTelegram200,
  GetTelegram401,
  GetTelegram404,
  GetTelegram500,
  GetXMessages200,
  GetXMessages401,
  GetXMessages500,
  PostChat200,
  PostChat400,
  PostChat401,
  PostChat429,
  PostChatBody,
  PostChatStream400,
  PostChatStream401,
  PostChatStream429,
  PostChatStreamBody,
  PostEmailChat200,
  PostEmailChat401,
  PostEmailChat429,
  PostEmailChatBody,
  PostNatieChat200,
  PostNatieChat401,
  PostNatieChat429,
  PostNatieChatBody,
  PostTelegram200,
  PostTelegram401,
  PostTelegram500,
  PostTelegramBody,
  PostXAccountBody,
  PostXChatBody
} from '.././models';

import { customInstance } from '../../custom-client';

export type getAuthLoginResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLoginResponseSuccess = (getAuthLoginResponse200) & {
  headers: Headers;
};
;

export type getAuthLoginResponse = (getAuthLoginResponseSuccess)

export const getGetAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const getAuthLogin = async ( options?: RequestInit): Promise<getAuthLoginResponse> => {
  
  return customInstance<getAuthLoginResponse>(getGetAuthLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthCallbackResponse200 = {
  data: void
  status: 200
}
    
export type getAuthCallbackResponseSuccess = (getAuthCallbackResponse200) & {
  headers: Headers;
};
;

export type getAuthCallbackResponse = (getAuthCallbackResponseSuccess)

export const getGetAuthCallbackUrl = () => {


  

  return `/auth/callback`
}

export const getAuthCallback = async ( options?: RequestInit): Promise<getAuthCallbackResponse> => {
  
  return customInstance<getAuthCallbackResponse>(getGetAuthCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthStatusResponse200 = {
  data: GetAuthStatus200
  status: 200
}

export type getAuthStatusResponse401 = {
  data: GetAuthStatus401
  status: 401
}
    
export type getAuthStatusResponseSuccess = (getAuthStatusResponse200) & {
  headers: Headers;
};
export type getAuthStatusResponseError = (getAuthStatusResponse401) & {
  headers: Headers;
};

export type getAuthStatusResponse = (getAuthStatusResponseSuccess | getAuthStatusResponseError)

export const getGetAuthStatusUrl = () => {


  

  return `/auth/status`
}

export const getAuthStatus = async ( options?: RequestInit): Promise<getAuthStatusResponse> => {
  
  return customInstance<getAuthStatusResponse>(getGetAuthStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthLogoutResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLogoutResponseSuccess = (getAuthLogoutResponse200) & {
  headers: Headers;
};
;

export type getAuthLogoutResponse = (getAuthLogoutResponseSuccess)

export const getGetAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const getAuthLogout = async ( options?: RequestInit): Promise<getAuthLogoutResponse> => {
  
  return customInstance<getAuthLogoutResponse>(getGetAuthLogoutUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthGoogleResponse302 = {
  data: unknown
  status: 302
}

export type getAuthGoogleResponse401 = {
  data: GetAuthGoogle401
  status: 401
}
    
;
export type getAuthGoogleResponseError = (getAuthGoogleResponse302 | getAuthGoogleResponse401) & {
  headers: Headers;
};

export type getAuthGoogleResponse = (getAuthGoogleResponseError)

export const getGetAuthGoogleUrl = () => {


  

  return `/auth/google`
}

export const getAuthGoogle = async ( options?: RequestInit): Promise<getAuthGoogleResponse> => {
  
  return customInstance<getAuthGoogleResponse>(getGetAuthGoogleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getOauthGoogleCallbackResponse302 = {
  data: unknown
  status: 302
}

export type getOauthGoogleCallbackResponse401 = {
  data: GetOauthGoogleCallback401
  status: 401
}
    
;
export type getOauthGoogleCallbackResponseError = (getOauthGoogleCallbackResponse302 | getOauthGoogleCallbackResponse401) & {
  headers: Headers;
};

export type getOauthGoogleCallbackResponse = (getOauthGoogleCallbackResponseError)

export const getGetOauthGoogleCallbackUrl = (params?: GetOauthGoogleCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/google/callback?${stringifiedParams}` : `/oauth/google/callback`
}

export const getOauthGoogleCallback = async (params?: GetOauthGoogleCallbackParams, options?: RequestInit): Promise<getOauthGoogleCallbackResponse> => {
  
  return customInstance<getOauthGoogleCallbackResponse>(getGetOauthGoogleCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getGmailAccountsResponse200 = {
  data: GetGmailAccounts200Item[]
  status: 200
}

export type getGmailAccountsResponse401 = {
  data: GetGmailAccounts401
  status: 401
}

export type getGmailAccountsResponse500 = {
  data: GetGmailAccounts500
  status: 500
}
    
export type getGmailAccountsResponseSuccess = (getGmailAccountsResponse200) & {
  headers: Headers;
};
export type getGmailAccountsResponseError = (getGmailAccountsResponse401 | getGmailAccountsResponse500) & {
  headers: Headers;
};

export type getGmailAccountsResponse = (getGmailAccountsResponseSuccess | getGmailAccountsResponseError)

export const getGetGmailAccountsUrl = () => {


  

  return `/gmail-accounts`
}

export const getGmailAccounts = async ( options?: RequestInit): Promise<getGmailAccountsResponse> => {
  
  return customInstance<getGmailAccountsResponse>(getGetGmailAccountsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type deleteGmailAccountsResponse200 = {
  data: DeleteGmailAccounts200
  status: 200
}

export type deleteGmailAccountsResponse401 = {
  data: DeleteGmailAccounts401
  status: 401
}

export type deleteGmailAccountsResponse404 = {
  data: DeleteGmailAccounts404
  status: 404
}

export type deleteGmailAccountsResponse500 = {
  data: DeleteGmailAccounts500
  status: 500
}
    
export type deleteGmailAccountsResponseSuccess = (deleteGmailAccountsResponse200) & {
  headers: Headers;
};
export type deleteGmailAccountsResponseError = (deleteGmailAccountsResponse401 | deleteGmailAccountsResponse404 | deleteGmailAccountsResponse500) & {
  headers: Headers;
};

export type deleteGmailAccountsResponse = (deleteGmailAccountsResponseSuccess | deleteGmailAccountsResponseError)

export const getDeleteGmailAccountsUrl = (params: DeleteGmailAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/gmail-accounts?${stringifiedParams}` : `/gmail-accounts`
}

export const deleteGmailAccounts = async (params: DeleteGmailAccountsParams, options?: RequestInit): Promise<deleteGmailAccountsResponse> => {
  
  return customInstance<deleteGmailAccountsResponse>(getDeleteGmailAccountsUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type getMessagesResponse200 = {
  data: GetMessages200
  status: 200
}

export type getMessagesResponse400 = {
  data: GetMessages400
  status: 400
}

export type getMessagesResponse401 = {
  data: GetMessages401
  status: 401
}

export type getMessagesResponse500 = {
  data: GetMessages500
  status: 500
}
    
export type getMessagesResponseSuccess = (getMessagesResponse200) & {
  headers: Headers;
};
export type getMessagesResponseError = (getMessagesResponse400 | getMessagesResponse401 | getMessagesResponse500) & {
  headers: Headers;
};

export type getMessagesResponse = (getMessagesResponseSuccess | getMessagesResponseError)

export const getGetMessagesUrl = (params: GetMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/messages?${stringifiedParams}` : `/messages`
}

export const getMessages = async (params: GetMessagesParams, options?: RequestInit): Promise<getMessagesResponse> => {
  
  return customInstance<getMessagesResponse>(getGetMessagesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postChatResponse200 = {
  data: PostChat200
  status: 200
}

export type postChatResponse400 = {
  data: PostChat400
  status: 400
}

export type postChatResponse401 = {
  data: PostChat401
  status: 401
}

export type postChatResponse429 = {
  data: PostChat429
  status: 429
}
    
export type postChatResponseSuccess = (postChatResponse200) & {
  headers: Headers;
};
export type postChatResponseError = (postChatResponse400 | postChatResponse401 | postChatResponse429) & {
  headers: Headers;
};

export type postChatResponse = (postChatResponseSuccess | postChatResponseError)

export const getPostChatUrl = () => {


  

  return `/chat`
}

export const postChat = async (postChatBody: PostChatBody, options?: RequestInit): Promise<postChatResponse> => {
  
  return customInstance<postChatResponse>(getPostChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postChatBody,)
  }
);}


export type postChatStreamResponse200 = {
  data: unknown
  status: 200
}

export type postChatStreamResponse400 = {
  data: PostChatStream400
  status: 400
}

export type postChatStreamResponse401 = {
  data: PostChatStream401
  status: 401
}

export type postChatStreamResponse429 = {
  data: PostChatStream429
  status: 429
}
    
export type postChatStreamResponseSuccess = (postChatStreamResponse200) & {
  headers: Headers;
};
export type postChatStreamResponseError = (postChatStreamResponse400 | postChatStreamResponse401 | postChatStreamResponse429) & {
  headers: Headers;
};

export type postChatStreamResponse = (postChatStreamResponseSuccess | postChatStreamResponseError)

export const getPostChatStreamUrl = () => {


  

  return `/chat/stream`
}

export const postChatStream = async (postChatStreamBody: PostChatStreamBody, options?: RequestInit): Promise<postChatStreamResponse> => {
  
  return customInstance<postChatStreamResponse>(getPostChatStreamUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postChatStreamBody,)
  }
);}


export type getXAccountResponse200 = {
  data: void
  status: 200
}
    
export type getXAccountResponseSuccess = (getXAccountResponse200) & {
  headers: Headers;
};
;

export type getXAccountResponse = (getXAccountResponseSuccess)

export const getGetXAccountUrl = () => {


  

  return `/x-account/`
}

export const getXAccount = async ( options?: RequestInit): Promise<getXAccountResponse> => {
  
  return customInstance<getXAccountResponse>(getGetXAccountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postXAccountResponse200 = {
  data: void
  status: 200
}
    
export type postXAccountResponseSuccess = (postXAccountResponse200) & {
  headers: Headers;
};
;

export type postXAccountResponse = (postXAccountResponseSuccess)

export const getPostXAccountUrl = () => {


  

  return `/x-account/`
}

export const postXAccount = async (postXAccountBody: PostXAccountBody, options?: RequestInit): Promise<postXAccountResponse> => {
  
  return customInstance<postXAccountResponse>(getPostXAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXAccountBody,)
  }
);}


export type deleteXAccountResponse200 = {
  data: void
  status: 200
}
    
export type deleteXAccountResponseSuccess = (deleteXAccountResponse200) & {
  headers: Headers;
};
;

export type deleteXAccountResponse = (deleteXAccountResponseSuccess)

export const getDeleteXAccountUrl = () => {


  

  return `/x-account/`
}

export const deleteXAccount = async ( options?: RequestInit): Promise<deleteXAccountResponse> => {
  
  return customInstance<deleteXAccountResponse>(getDeleteXAccountUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type postEmailChatResponse200 = {
  data: PostEmailChat200
  status: 200
}

export type postEmailChatResponse401 = {
  data: PostEmailChat401
  status: 401
}

export type postEmailChatResponse429 = {
  data: PostEmailChat429
  status: 429
}
    
export type postEmailChatResponseSuccess = (postEmailChatResponse200) & {
  headers: Headers;
};
export type postEmailChatResponseError = (postEmailChatResponse401 | postEmailChatResponse429) & {
  headers: Headers;
};

export type postEmailChatResponse = (postEmailChatResponseSuccess | postEmailChatResponseError)

export const getPostEmailChatUrl = () => {


  

  return `/email/chat`
}

export const postEmailChat = async (postEmailChatBody: PostEmailChatBody, options?: RequestInit): Promise<postEmailChatResponse> => {
  
  return customInstance<postEmailChatResponse>(getPostEmailChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postEmailChatBody,)
  }
);}


export type getXMessagesResponse200 = {
  data: GetXMessages200
  status: 200
}

export type getXMessagesResponse401 = {
  data: GetXMessages401
  status: 401
}

export type getXMessagesResponse500 = {
  data: GetXMessages500
  status: 500
}
    
export type getXMessagesResponseSuccess = (getXMessagesResponse200) & {
  headers: Headers;
};
export type getXMessagesResponseError = (getXMessagesResponse401 | getXMessagesResponse500) & {
  headers: Headers;
};

export type getXMessagesResponse = (getXMessagesResponseSuccess | getXMessagesResponseError)

export const getGetXMessagesUrl = () => {


  

  return `/x/messages`
}

export const getXMessages = async ( options?: RequestInit): Promise<getXMessagesResponse> => {
  
  return customInstance<getXMessagesResponse>(getGetXMessagesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postXChatResponse200 = {
  data: void
  status: 200
}
    
export type postXChatResponseSuccess = (postXChatResponse200) & {
  headers: Headers;
};
;

export type postXChatResponse = (postXChatResponseSuccess)

export const getPostXChatUrl = () => {


  

  return `/x/chat`
}

export const postXChat = async (postXChatBody: PostXChatBody, options?: RequestInit): Promise<postXChatResponse> => {
  
  return customInstance<postXChatResponse>(getPostXChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXChatBody,)
  }
);}


export type getNatieMessagesResponse200 = {
  data: GetNatieMessages200
  status: 200
}

export type getNatieMessagesResponse401 = {
  data: GetNatieMessages401
  status: 401
}

export type getNatieMessagesResponse500 = {
  data: GetNatieMessages500
  status: 500
}
    
export type getNatieMessagesResponseSuccess = (getNatieMessagesResponse200) & {
  headers: Headers;
};
export type getNatieMessagesResponseError = (getNatieMessagesResponse401 | getNatieMessagesResponse500) & {
  headers: Headers;
};

export type getNatieMessagesResponse = (getNatieMessagesResponseSuccess | getNatieMessagesResponseError)

export const getGetNatieMessagesUrl = () => {


  

  return `/natie/messages`
}

export const getNatieMessages = async ( options?: RequestInit): Promise<getNatieMessagesResponse> => {
  
  return customInstance<getNatieMessagesResponse>(getGetNatieMessagesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postNatieChatResponse200 = {
  data: PostNatieChat200
  status: 200
}

export type postNatieChatResponse401 = {
  data: PostNatieChat401
  status: 401
}

export type postNatieChatResponse429 = {
  data: PostNatieChat429
  status: 429
}
    
export type postNatieChatResponseSuccess = (postNatieChatResponse200) & {
  headers: Headers;
};
export type postNatieChatResponseError = (postNatieChatResponse401 | postNatieChatResponse429) & {
  headers: Headers;
};

export type postNatieChatResponse = (postNatieChatResponseSuccess | postNatieChatResponseError)

export const getPostNatieChatUrl = () => {


  

  return `/natie/chat`
}

export const postNatieChat = async (postNatieChatBody: PostNatieChatBody, options?: RequestInit): Promise<postNatieChatResponse> => {
  
  return customInstance<postNatieChatResponse>(getPostNatieChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postNatieChatBody,)
  }
);}


export type getTelegramResponse200 = {
  data: GetTelegram200
  status: 200
}

export type getTelegramResponse401 = {
  data: GetTelegram401
  status: 401
}

export type getTelegramResponse404 = {
  data: GetTelegram404
  status: 404
}

export type getTelegramResponse500 = {
  data: GetTelegram500
  status: 500
}
    
export type getTelegramResponseSuccess = (getTelegramResponse200) & {
  headers: Headers;
};
export type getTelegramResponseError = (getTelegramResponse401 | getTelegramResponse404 | getTelegramResponse500) & {
  headers: Headers;
};

export type getTelegramResponse = (getTelegramResponseSuccess | getTelegramResponseError)

export const getGetTelegramUrl = () => {


  

  return `/telegram/`
}

export const getTelegram = async ( options?: RequestInit): Promise<getTelegramResponse> => {
  
  return customInstance<getTelegramResponse>(getGetTelegramUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postTelegramResponse200 = {
  data: PostTelegram200
  status: 200
}

export type postTelegramResponse401 = {
  data: PostTelegram401
  status: 401
}

export type postTelegramResponse500 = {
  data: PostTelegram500
  status: 500
}
    
export type postTelegramResponseSuccess = (postTelegramResponse200) & {
  headers: Headers;
};
export type postTelegramResponseError = (postTelegramResponse401 | postTelegramResponse500) & {
  headers: Headers;
};

export type postTelegramResponse = (postTelegramResponseSuccess | postTelegramResponseError)

export const getPostTelegramUrl = () => {


  

  return `/telegram/`
}

export const postTelegram = async (postTelegramBody: PostTelegramBody, options?: RequestInit): Promise<postTelegramResponse> => {
  
  return customInstance<postTelegramResponse>(getPostTelegramUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postTelegramBody,)
  }
);}


export type deleteTelegramResponse200 = {
  data: DeleteTelegram200
  status: 200
}

export type deleteTelegramResponse401 = {
  data: DeleteTelegram401
  status: 401
}

export type deleteTelegramResponse404 = {
  data: DeleteTelegram404
  status: 404
}

export type deleteTelegramResponse500 = {
  data: DeleteTelegram500
  status: 500
}
    
export type deleteTelegramResponseSuccess = (deleteTelegramResponse200) & {
  headers: Headers;
};
export type deleteTelegramResponseError = (deleteTelegramResponse401 | deleteTelegramResponse404 | deleteTelegramResponse500) & {
  headers: Headers;
};

export type deleteTelegramResponse = (deleteTelegramResponseSuccess | deleteTelegramResponseError)

export const getDeleteTelegramUrl = () => {


  

  return `/telegram/`
}

export const deleteTelegram = async ( options?: RequestInit): Promise<deleteTelegramResponse> => {
  
  return customInstance<deleteTelegramResponse>(getDeleteTelegramUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


