/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteGmailAccounts200,
  DeleteGmailAccounts401,
  DeleteGmailAccounts404,
  DeleteGmailAccountsParams,
  GetAuthStatus200,
  GetAuthStatus401,
  GetGmailAccounts200Item,
  GetGmailAccounts401,
  PostEmailChatBody,
  PostNatieChatBody,
  PostXAccountBody,
  PostXChatBody
} from '.././models';

import { customInstance } from '../../custom-client';

export type getAuthLoginResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLoginResponseSuccess = (getAuthLoginResponse200) & {
  headers: Headers;
};
;

export type getAuthLoginResponse = (getAuthLoginResponseSuccess)

export const getGetAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const getAuthLogin = async ( options?: RequestInit): Promise<getAuthLoginResponse> => {
  
  return customInstance<getAuthLoginResponse>(getGetAuthLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthCallbackResponse200 = {
  data: void
  status: 200
}
    
export type getAuthCallbackResponseSuccess = (getAuthCallbackResponse200) & {
  headers: Headers;
};
;

export type getAuthCallbackResponse = (getAuthCallbackResponseSuccess)

export const getGetAuthCallbackUrl = () => {


  

  return `/auth/callback`
}

export const getAuthCallback = async ( options?: RequestInit): Promise<getAuthCallbackResponse> => {
  
  return customInstance<getAuthCallbackResponse>(getGetAuthCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthStatusResponse200 = {
  data: GetAuthStatus200
  status: 200
}

export type getAuthStatusResponse401 = {
  data: GetAuthStatus401
  status: 401
}
    
export type getAuthStatusResponseSuccess = (getAuthStatusResponse200) & {
  headers: Headers;
};
export type getAuthStatusResponseError = (getAuthStatusResponse401) & {
  headers: Headers;
};

export type getAuthStatusResponse = (getAuthStatusResponseSuccess | getAuthStatusResponseError)

export const getGetAuthStatusUrl = () => {


  

  return `/auth/status`
}

export const getAuthStatus = async ( options?: RequestInit): Promise<getAuthStatusResponse> => {
  
  return customInstance<getAuthStatusResponse>(getGetAuthStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthLogoutResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLogoutResponseSuccess = (getAuthLogoutResponse200) & {
  headers: Headers;
};
;

export type getAuthLogoutResponse = (getAuthLogoutResponseSuccess)

export const getGetAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const getAuthLogout = async ( options?: RequestInit): Promise<getAuthLogoutResponse> => {
  
  return customInstance<getAuthLogoutResponse>(getGetAuthLogoutUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthGoogleResponse200 = {
  data: void
  status: 200
}
    
export type getAuthGoogleResponseSuccess = (getAuthGoogleResponse200) & {
  headers: Headers;
};
;

export type getAuthGoogleResponse = (getAuthGoogleResponseSuccess)

export const getGetAuthGoogleUrl = () => {


  

  return `/auth/google`
}

export const getAuthGoogle = async ( options?: RequestInit): Promise<getAuthGoogleResponse> => {
  
  return customInstance<getAuthGoogleResponse>(getGetAuthGoogleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getOauthGoogleCallbackResponse200 = {
  data: void
  status: 200
}
    
export type getOauthGoogleCallbackResponseSuccess = (getOauthGoogleCallbackResponse200) & {
  headers: Headers;
};
;

export type getOauthGoogleCallbackResponse = (getOauthGoogleCallbackResponseSuccess)

export const getGetOauthGoogleCallbackUrl = () => {


  

  return `/oauth/google/callback`
}

export const getOauthGoogleCallback = async ( options?: RequestInit): Promise<getOauthGoogleCallbackResponse> => {
  
  return customInstance<getOauthGoogleCallbackResponse>(getGetOauthGoogleCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getGmailAccountsResponse200 = {
  data: GetGmailAccounts200Item[]
  status: 200
}

export type getGmailAccountsResponse401 = {
  data: GetGmailAccounts401
  status: 401
}
    
export type getGmailAccountsResponseSuccess = (getGmailAccountsResponse200) & {
  headers: Headers;
};
export type getGmailAccountsResponseError = (getGmailAccountsResponse401) & {
  headers: Headers;
};

export type getGmailAccountsResponse = (getGmailAccountsResponseSuccess | getGmailAccountsResponseError)

export const getGetGmailAccountsUrl = () => {


  

  return `/gmail-accounts`
}

export const getGmailAccounts = async ( options?: RequestInit): Promise<getGmailAccountsResponse> => {
  
  return customInstance<getGmailAccountsResponse>(getGetGmailAccountsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type deleteGmailAccountsResponse200 = {
  data: DeleteGmailAccounts200
  status: 200
}

export type deleteGmailAccountsResponse401 = {
  data: DeleteGmailAccounts401
  status: 401
}

export type deleteGmailAccountsResponse404 = {
  data: DeleteGmailAccounts404
  status: 404
}
    
export type deleteGmailAccountsResponseSuccess = (deleteGmailAccountsResponse200) & {
  headers: Headers;
};
export type deleteGmailAccountsResponseError = (deleteGmailAccountsResponse401 | deleteGmailAccountsResponse404) & {
  headers: Headers;
};

export type deleteGmailAccountsResponse = (deleteGmailAccountsResponseSuccess | deleteGmailAccountsResponseError)

export const getDeleteGmailAccountsUrl = (params: DeleteGmailAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/gmail-accounts?${stringifiedParams}` : `/gmail-accounts`
}

export const deleteGmailAccounts = async (params: DeleteGmailAccountsParams, options?: RequestInit): Promise<deleteGmailAccountsResponse> => {
  
  return customInstance<deleteGmailAccountsResponse>(getDeleteGmailAccountsUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type getXAccountResponse200 = {
  data: void
  status: 200
}
    
export type getXAccountResponseSuccess = (getXAccountResponse200) & {
  headers: Headers;
};
;

export type getXAccountResponse = (getXAccountResponseSuccess)

export const getGetXAccountUrl = () => {


  

  return `/x-account/`
}

export const getXAccount = async ( options?: RequestInit): Promise<getXAccountResponse> => {
  
  return customInstance<getXAccountResponse>(getGetXAccountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postXAccountResponse200 = {
  data: void
  status: 200
}
    
export type postXAccountResponseSuccess = (postXAccountResponse200) & {
  headers: Headers;
};
;

export type postXAccountResponse = (postXAccountResponseSuccess)

export const getPostXAccountUrl = () => {


  

  return `/x-account/`
}

export const postXAccount = async (postXAccountBody: PostXAccountBody, options?: RequestInit): Promise<postXAccountResponse> => {
  
  return customInstance<postXAccountResponse>(getPostXAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXAccountBody,)
  }
);}


export type deleteXAccountResponse200 = {
  data: void
  status: 200
}
    
export type deleteXAccountResponseSuccess = (deleteXAccountResponse200) & {
  headers: Headers;
};
;

export type deleteXAccountResponse = (deleteXAccountResponseSuccess)

export const getDeleteXAccountUrl = () => {


  

  return `/x-account/`
}

export const deleteXAccount = async ( options?: RequestInit): Promise<deleteXAccountResponse> => {
  
  return customInstance<deleteXAccountResponse>(getDeleteXAccountUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type postEmailChatResponse200 = {
  data: void
  status: 200
}
    
export type postEmailChatResponseSuccess = (postEmailChatResponse200) & {
  headers: Headers;
};
;

export type postEmailChatResponse = (postEmailChatResponseSuccess)

export const getPostEmailChatUrl = () => {


  

  return `/email/chat`
}

export const postEmailChat = async (postEmailChatBody: PostEmailChatBody, options?: RequestInit): Promise<postEmailChatResponse> => {
  
  return customInstance<postEmailChatResponse>(getPostEmailChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postEmailChatBody,)
  }
);}


export type postXChatResponse200 = {
  data: void
  status: 200
}
    
export type postXChatResponseSuccess = (postXChatResponse200) & {
  headers: Headers;
};
;

export type postXChatResponse = (postXChatResponseSuccess)

export const getPostXChatUrl = () => {


  

  return `/x/chat`
}

export const postXChat = async (postXChatBody: PostXChatBody, options?: RequestInit): Promise<postXChatResponse> => {
  
  return customInstance<postXChatResponse>(getPostXChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXChatBody,)
  }
);}


export type postNatieChatResponse200 = {
  data: void
  status: 200
}
    
export type postNatieChatResponseSuccess = (postNatieChatResponse200) & {
  headers: Headers;
};
;

export type postNatieChatResponse = (postNatieChatResponseSuccess)

export const getPostNatieChatUrl = () => {


  

  return `/natie/chat`
}

export const postNatieChat = async (postNatieChatBody: PostNatieChatBody, options?: RequestInit): Promise<postNatieChatResponse> => {
  
  return customInstance<postNatieChatResponse>(getPostNatieChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postNatieChatBody,)
  }
);}


