/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthStatus200User } from './getAuthStatus200User';

export type GetAuthStatus200 = {
  /** @nullable */
  user: GetAuthStatus200User;
};
