/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetGoogleCalendarAccounts200ItemProvider = typeof GetGoogleCalendarAccounts200ItemProvider[keyof typeof GetGoogleCalendarAccounts200ItemProvider];


export const GetGoogleCalendarAccounts200ItemProvider = {
  google: 'google',
} as const;
