/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetMessages200MessagesItemChannel = typeof GetMessages200MessagesItemChannel[keyof typeof GetMessages200MessagesItemChannel];


export const GetMessages200MessagesItemChannel = {
  web: 'web',
  telegram: 'telegram',
} as const;
