/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagesChatType = typeof GetMessagesChatType[keyof typeof GetMessagesChatType];


export const GetMessagesChatType = {
  natie: 'natie',
  email: 'email',
  x: 'x',
  telegram: 'telegram',
} as const;
