/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessages200MessagesItemToolCallsItemArgs } from './getMessages200MessagesItemToolCallsItemArgs';

export type GetMessages200MessagesItemToolCallsItem = {
  name: string;
  args: GetMessages200MessagesItemToolCallsItemArgs;
  type: string;
  id: string;
};
