/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessages200MessagesItem } from './getMessages200MessagesItem';

export type GetMessages200 = {
  messages: GetMessages200MessagesItem[];
};
