/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetMessages200MessagesItemType = typeof GetMessages200MessagesItemType[keyof typeof GetMessages200MessagesItemType];


export const GetMessages200MessagesItemType = {
  human: 'human',
  ai: 'ai',
  tool: 'tool',
} as const;
