/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetNatieMessages200MessagesItemType = typeof GetNatieMessages200MessagesItemType[keyof typeof GetNatieMessages200MessagesItemType];


export const GetNatieMessages200MessagesItemType = {
  human: 'human',
  ai: 'ai',
  tool: 'tool',
} as const;
