/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetNatieMessages200MessagesItemChannel } from './getNatieMessages200MessagesItemChannel';
import type { GetNatieMessages200MessagesItemResponseMetadata } from './getNatieMessages200MessagesItemResponseMetadata';
import type { GetNatieMessages200MessagesItemToolCallsItem } from './getNatieMessages200MessagesItemToolCallsItem';
import type { GetNatieMessages200MessagesItemType } from './getNatieMessages200MessagesItemType';

export type GetNatieMessages200MessagesItem = {
  id: string;
  /** @nullable */
  name: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
  conversationId: string;
  type: GetNatieMessages200MessagesItemType;
  content: string;
  responseMetadata: GetNatieMessages200MessagesItemResponseMetadata;
  /** @nullable */
  toolCalls: GetNatieMessages200MessagesItemToolCallsItem[] | null;
  invalidToolCalls: unknown | null;
  /** @nullable */
  toolCallId: string | null;
  channel: GetNatieMessages200MessagesItemChannel;
};
