/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetNatieMessages200MessagesItemToolCalls = {
  name: string;
  args: {
  query: string;
};
  type: string;
  id: string;
}[] | unknown | null;
