/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetNatieMessages200MessagesItemChannel = typeof GetNatieMessages200MessagesItemChannel[keyof typeof GetNatieMessages200MessagesItemChannel];


export const GetNatieMessages200MessagesItemChannel = {
  web: 'web',
  telegram: 'telegram',
} as const;
