/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetNatieMessages200MessagesItemToolCallsItemArgs } from './getNatieMessages200MessagesItemToolCallsItemArgs';

export type GetNatieMessages200MessagesItemToolCallsItem = {
  name: string;
  args: GetNatieMessages200MessagesItemToolCallsItemArgs;
  type: string;
  id: string;
};
