/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetNatieMessages200MessagesItem } from './getNatieMessages200MessagesItem';

export type GetNatieMessages200 = {
  messages: GetNatieMessages200MessagesItem[];
};
