/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetTokenUsageSummary200UsageItem = {
  id: string;
  modelName: string;
  modelProvider: string;
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  cachedTokens: number;
  reasoningTokens: number;
  inputPricePerToken: string;
  outputPricePerToken: string;
  estimatedCost: string;
};
