/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetXMessages200MessagesItemChannel } from './getXMessages200MessagesItemChannel';
import type { GetXMessages200MessagesItemResponseMetadata } from './getXMessages200MessagesItemResponseMetadata';
import type { GetXMessages200MessagesItemToolCallsItem } from './getXMessages200MessagesItemToolCallsItem';
import type { GetXMessages200MessagesItemType } from './getXMessages200MessagesItemType';

export type GetXMessages200MessagesItem = {
  id: string;
  /** @nullable */
  name: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
  conversationId: string;
  type: GetXMessages200MessagesItemType;
  content: string;
  responseMetadata: GetXMessages200MessagesItemResponseMetadata;
  /** @nullable */
  toolCalls: GetXMessages200MessagesItemToolCallsItem[] | null;
  invalidToolCalls: unknown | null;
  /** @nullable */
  toolCallId: string | null;
  channel: GetXMessages200MessagesItemChannel;
};
