/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetXMessages200MessagesItemChannel = typeof GetXMessages200MessagesItemChannel[keyof typeof GetXMessages200MessagesItemChannel];


export const GetXMessages200MessagesItemChannel = {
  web: 'web',
  telegram: 'telegram',
} as const;
