/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetXMessages200MessagesItem } from './getXMessages200MessagesItem';

export type GetXMessages200 = {
  messages: GetXMessages200MessagesItem[];
};
