/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { GetXMessages200MessagesItemToolCallsItemArgs } from './getXMessages200MessagesItemToolCallsItemArgs';

export type GetXMessages200MessagesItemToolCallsItem = {
  name: string;
  args: GetXMessages200MessagesItemToolCallsItemArgs;
  type: string;
  id: string;
};
