/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export * from './deleteGmailAccounts200';
export * from './deleteGmailAccounts401';
export * from './deleteGmailAccounts404';
export * from './deleteGmailAccounts500';
export * from './deleteGmailAccountsParams';
export * from './deleteTelegram200';
export * from './deleteTelegram401';
export * from './deleteTelegram404';
export * from './deleteTelegram500';
export * from './getAuthGoogle401';
export * from './getAuthStatus200';
export * from './getAuthStatus200User';
export * from './getAuthStatus401';
export * from './getGmailAccounts200Item';
export * from './getGmailAccounts200ItemProvider';
export * from './getGmailAccounts401';
export * from './getGmailAccounts500';
export * from './getOauthGoogleCallback401';
export * from './getOauthGoogleCallbackParams';
export * from './getTelegram200';
export * from './getTelegram401';
export * from './getTelegram404';
export * from './getTelegram500';
export * from './postEmailChatBody';
export * from './postEmailChatBodyType';
export * from './postNatieChatBody';
export * from './postNatieChatBodyType';
export * from './postTelegram200';
export * from './postTelegram401';
export * from './postTelegram500';
export * from './postTelegramBody';
export * from './postXAccountBody';
export * from './postXChatBody';
export * from './postXChatBodyType';