/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostEmailChat200MessagesItemResponseMetadata = {
  tokenUsage: {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
};
  finish_reason: string;
  model_provider: string;
  model_name: string;
  usage: {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  prompt_tokens_details: {
  cached_tokens: number;
  audio_tokens: number;
};
  completion_tokens_details: {
  reasoning_tokens: number;
  audio_tokens: number;
  accepted_prediction_tokens: number;
  rejected_prediction_tokens: number;
};
};
  system_fingerprint: string;
} | unknown | null;
