/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostChat200MessagesItemChannel = typeof PostChat200MessagesItemChannel[keyof typeof PostChat200MessagesItemChannel];


export const PostChat200MessagesItemChannel = {
  web: 'web',
  telegram: 'telegram',
} as const;
