/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostChatBodyChatType } from './postChatBodyChatType';

export type PostChatBody = {
  chatType: PostChatBodyChatType;
  /** @minLength 1 */
  message: string;
};
