/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostNatieChat200MessagesItem } from './postNatieChat200MessagesItem';

export type PostNatieChat200 = {
  messages: PostNatieChat200MessagesItem[];
};
