/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostNatieChat200MessagesItemType = typeof PostNatieChat200MessagesItemType[keyof typeof PostNatieChat200MessagesItemType];


export const PostNatieChat200MessagesItemType = {
  human: 'human',
  ai: 'ai',
  tool: 'tool',
} as const;
