/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostChat200MessagesItemType = typeof PostChat200MessagesItemType[keyof typeof PostChat200MessagesItemType];


export const PostChat200MessagesItemType = {
  human: 'human',
  ai: 'ai',
  tool: 'tool',
} as const;
