/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostChat200MessagesItemToolCallsItemArgs } from './postChat200MessagesItemToolCallsItemArgs';

export type PostChat200MessagesItemToolCallsItem = {
  name: string;
  args: PostChat200MessagesItemToolCallsItemArgs;
  type: string;
  id: string;
};
