/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostEmailChat200MessagesItem } from './postEmailChat200MessagesItem';

export type PostEmailChat200 = {
  messages: PostEmailChat200MessagesItem[];
};
