/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostNatieChat200MessagesItemChannel = typeof PostNatieChat200MessagesItemChannel[keyof typeof PostNatieChat200MessagesItemChannel];


export const PostNatieChat200MessagesItemChannel = {
  web: 'web',
  telegram: 'telegram',
} as const;
