/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostEmailChat200MessagesItemChannel = typeof PostEmailChat200MessagesItemChannel[keyof typeof PostEmailChat200MessagesItemChannel];


export const PostEmailChat200MessagesItemChannel = {
  web: 'web',
  telegram: 'telegram',
} as const;
