/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostChatStreamBodyChatType } from './postChatStreamBodyChatType';

export type PostChatStreamBody = {
  chatType: PostChatStreamBodyChatType;
  /** @minLength 1 */
  message: string;
};
