/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostNatieChat200MessagesItemToolCallsItemArgs } from './postNatieChat200MessagesItemToolCallsItemArgs';

export type PostNatieChat200MessagesItemToolCallsItem = {
  name: string;
  args: PostNatieChat200MessagesItemToolCallsItemArgs;
  type: string;
  id: string;
};
