/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostChat200MessagesItem } from './postChat200MessagesItem';

export type PostChat200 = {
  messages: PostChat200MessagesItem[];
};
