/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostEmailChat200MessagesItemToolCallsItemArgs } from './postEmailChat200MessagesItemToolCallsItemArgs';

export type PostEmailChat200MessagesItemToolCallsItem = {
  name: string;
  args: PostEmailChat200MessagesItemToolCallsItemArgs;
  type: string;
  id: string;
};
