/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostXChatBodyType = typeof PostXChatBodyType[keyof typeof PostXChatBodyType];


export const PostXChatBodyType = {
  stream: 'stream',
  invoke: 'invoke',
} as const;
