/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostEmailChat200MessagesItemType = typeof PostEmailChat200MessagesItemType[keyof typeof PostEmailChat200MessagesItemType];


export const PostEmailChat200MessagesItemType = {
  human: 'human',
  ai: 'ai',
  tool: 'tool',
} as const;
