/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  GetTokenUsageSummary200,
  GetTokenUsageSummary401,
  GetTokenUsageSummary500
} from '../../api/models';

import { customInstance } from '../../custom-client';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
export type getTokenUsageSummaryResponse200 = {
  data: GetTokenUsageSummary200
  status: 200
}

export type getTokenUsageSummaryResponse401 = {
  data: GetTokenUsageSummary401
  status: 401
}

export type getTokenUsageSummaryResponse500 = {
  data: GetTokenUsageSummary500
  status: 500
}
    
export type getTokenUsageSummaryResponseSuccess = (getTokenUsageSummaryResponse200) & {
  headers: Headers;
};
export type getTokenUsageSummaryResponseError = (getTokenUsageSummaryResponse401 | getTokenUsageSummaryResponse500) & {
  headers: Headers;
};

export type getTokenUsageSummaryResponse = (getTokenUsageSummaryResponseSuccess | getTokenUsageSummaryResponseError)

export const getGetTokenUsageSummaryUrl = () => {


  

  return `/token-usage/summary`
}

export const getTokenUsageSummary = async ( options?: RequestInit): Promise<getTokenUsageSummaryResponse> => {
  
  return customInstance<getTokenUsageSummaryResponse>(getGetTokenUsageSummaryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetTokenUsageSummaryKey = () => [`/token-usage/summary`] as const;

export type GetTokenUsageSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getTokenUsageSummary>>>

export const useGetTokenUsageSummary = <TError = GetTokenUsageSummary401 | GetTokenUsageSummary500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTokenUsageSummary>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTokenUsageSummaryKey() : null);
  const swrFn = () => getTokenUsageSummary(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
