/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type GetGmailAccounts200ItemProvider = typeof GetGmailAccounts200ItemProvider[keyof typeof GetGmailAccounts200ItemProvider];


export const GetGmailAccounts200ItemProvider = {
  gmail: 'gmail',
} as const;
