/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostNatieChatBodyType = typeof PostNatieChatBodyType[keyof typeof PostNatieChatBodyType];


export const PostNatieChatBodyType = {
  stream: 'stream',
  invoke: 'invoke',
} as const;
