/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostXChatBodyType } from './postXChatBodyType';

export type PostXChatBody = {
  /** @minLength 1 */
  message: string;
  type: PostXChatBodyType;
  agentConversationId: string;
};
