/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  DeleteGmailAccounts200,
  DeleteGmailAccounts401,
  DeleteGmailAccounts404,
  DeleteGmailAccounts500,
  DeleteGmailAccountsParams,
  DeleteGoogleCalendarAccounts200,
  DeleteGoogleCalendarAccounts401,
  DeleteGoogleCalendarAccounts404,
  DeleteGoogleCalendarAccounts500,
  DeleteGoogleCalendarAccountsParams,
  DeleteTelegram200,
  DeleteTelegram401,
  DeleteTelegram404,
  DeleteTelegram500,
  DeleteXAccount200,
  DeleteXAccount401,
  DeleteXAccount404,
  DeleteXAccount500,
  GetAuthCallback400,
  GetAuthCallback500,
  GetAuthCallbackParams,
  GetAuthLogin500,
  GetAuthLogout500,
  GetAuthStatus200,
  GetAuthStatus401,
  GetGmailAccounts200Item,
  GetGmailAccounts401,
  GetGmailAccounts500,
  GetGoogleCalendarAccounts200Item,
  GetGoogleCalendarAccounts401,
  GetGoogleCalendarAccounts500,
  GetMessages200,
  GetMessages400,
  GetMessages401,
  GetMessages500,
  GetMessagesParams,
  GetOauthGoogleCalendar401,
  GetOauthGoogleCallback401,
  GetOauthGoogleCallbackParams,
  GetOauthGoogleGmail401,
  GetTelegram200,
  GetTelegram401,
  GetTelegram404,
  GetTelegram500,
  GetXAccount200,
  GetXAccount401,
  GetXAccount404,
  GetXAccount500,
  PostChat200,
  PostChat400,
  PostChat401,
  PostChat429,
  PostChatBody,
  PostChatStream400,
  PostChatStream401,
  PostChatStream429,
  PostChatStreamBody,
  PostTelegram200,
  PostTelegram400,
  PostTelegram401,
  PostTelegram500,
  PostTelegramBody,
  PostXAccount200,
  PostXAccount401,
  PostXAccount500,
  PostXAccountBody
} from '../../api/models';

import { customInstance } from '../../custom-client';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
export type getAuthLoginResponse302 = {
  data: unknown
  status: 302
}

export type getAuthLoginResponse500 = {
  data: GetAuthLogin500
  status: 500
}
    
;
export type getAuthLoginResponseError = (getAuthLoginResponse302 | getAuthLoginResponse500) & {
  headers: Headers;
};

export type getAuthLoginResponse = (getAuthLoginResponseError)

export const getGetAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const getAuthLogin = async ( options?: RequestInit): Promise<getAuthLoginResponse> => {
  
  return customInstance<getAuthLoginResponse>(getGetAuthLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthLoginKey = () => [`/auth/login`] as const;

export type GetAuthLoginQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthLogin>>>

export const useGetAuthLogin = <TError = unknown | GetAuthLogin500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthLogin>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthLoginKey() : null);
  const swrFn = () => getAuthLogin(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getAuthCallbackResponse302 = {
  data: unknown
  status: 302
}

export type getAuthCallbackResponse400 = {
  data: GetAuthCallback400
  status: 400
}

export type getAuthCallbackResponse500 = {
  data: GetAuthCallback500
  status: 500
}
    
;
export type getAuthCallbackResponseError = (getAuthCallbackResponse302 | getAuthCallbackResponse400 | getAuthCallbackResponse500) & {
  headers: Headers;
};

export type getAuthCallbackResponse = (getAuthCallbackResponseError)

export const getGetAuthCallbackUrl = (params?: GetAuthCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/callback?${stringifiedParams}` : `/auth/callback`
}

export const getAuthCallback = async (params?: GetAuthCallbackParams, options?: RequestInit): Promise<getAuthCallbackResponse> => {
  
  return customInstance<getAuthCallbackResponse>(getGetAuthCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthCallbackKey = (params?: GetAuthCallbackParams,) => [`/auth/callback`, ...(params ? [params]: [])] as const;

export type GetAuthCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthCallback>>>

export const useGetAuthCallback = <TError = unknown | GetAuthCallback400 | GetAuthCallback500>(
  params?: GetAuthCallbackParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthCallback>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthCallbackKey(params) : null);
  const swrFn = () => getAuthCallback(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getAuthStatusResponse200 = {
  data: GetAuthStatus200
  status: 200
}

export type getAuthStatusResponse401 = {
  data: GetAuthStatus401
  status: 401
}
    
export type getAuthStatusResponseSuccess = (getAuthStatusResponse200) & {
  headers: Headers;
};
export type getAuthStatusResponseError = (getAuthStatusResponse401) & {
  headers: Headers;
};

export type getAuthStatusResponse = (getAuthStatusResponseSuccess | getAuthStatusResponseError)

export const getGetAuthStatusUrl = () => {


  

  return `/auth/status`
}

export const getAuthStatus = async ( options?: RequestInit): Promise<getAuthStatusResponse> => {
  
  return customInstance<getAuthStatusResponse>(getGetAuthStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthStatusKey = () => [`/auth/status`] as const;

export type GetAuthStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthStatus>>>

export const useGetAuthStatus = <TError = GetAuthStatus401>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthStatus>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthStatusKey() : null);
  const swrFn = () => getAuthStatus(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getAuthLogoutResponse302 = {
  data: unknown
  status: 302
}

export type getAuthLogoutResponse500 = {
  data: GetAuthLogout500
  status: 500
}
    
;
export type getAuthLogoutResponseError = (getAuthLogoutResponse302 | getAuthLogoutResponse500) & {
  headers: Headers;
};

export type getAuthLogoutResponse = (getAuthLogoutResponseError)

export const getGetAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const getAuthLogout = async ( options?: RequestInit): Promise<getAuthLogoutResponse> => {
  
  return customInstance<getAuthLogoutResponse>(getGetAuthLogoutUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthLogoutKey = () => [`/auth/logout`] as const;

export type GetAuthLogoutQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthLogout>>>

export const useGetAuthLogout = <TError = unknown | GetAuthLogout500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthLogout>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthLogoutKey() : null);
  const swrFn = () => getAuthLogout(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getOauthGoogleGmailResponse302 = {
  data: unknown
  status: 302
}

export type getOauthGoogleGmailResponse401 = {
  data: GetOauthGoogleGmail401
  status: 401
}
    
;
export type getOauthGoogleGmailResponseError = (getOauthGoogleGmailResponse302 | getOauthGoogleGmailResponse401) & {
  headers: Headers;
};

export type getOauthGoogleGmailResponse = (getOauthGoogleGmailResponseError)

export const getGetOauthGoogleGmailUrl = () => {


  

  return `/oauth/google/gmail`
}

export const getOauthGoogleGmail = async ( options?: RequestInit): Promise<getOauthGoogleGmailResponse> => {
  
  return customInstance<getOauthGoogleGmailResponse>(getGetOauthGoogleGmailUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetOauthGoogleGmailKey = () => [`/oauth/google/gmail`] as const;

export type GetOauthGoogleGmailQueryResult = NonNullable<Awaited<ReturnType<typeof getOauthGoogleGmail>>>

export const useGetOauthGoogleGmail = <TError = unknown | GetOauthGoogleGmail401>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOauthGoogleGmail>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOauthGoogleGmailKey() : null);
  const swrFn = () => getOauthGoogleGmail(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getOauthGoogleCalendarResponse302 = {
  data: unknown
  status: 302
}

export type getOauthGoogleCalendarResponse401 = {
  data: GetOauthGoogleCalendar401
  status: 401
}
    
;
export type getOauthGoogleCalendarResponseError = (getOauthGoogleCalendarResponse302 | getOauthGoogleCalendarResponse401) & {
  headers: Headers;
};

export type getOauthGoogleCalendarResponse = (getOauthGoogleCalendarResponseError)

export const getGetOauthGoogleCalendarUrl = () => {


  

  return `/oauth/google/calendar`
}

export const getOauthGoogleCalendar = async ( options?: RequestInit): Promise<getOauthGoogleCalendarResponse> => {
  
  return customInstance<getOauthGoogleCalendarResponse>(getGetOauthGoogleCalendarUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetOauthGoogleCalendarKey = () => [`/oauth/google/calendar`] as const;

export type GetOauthGoogleCalendarQueryResult = NonNullable<Awaited<ReturnType<typeof getOauthGoogleCalendar>>>

export const useGetOauthGoogleCalendar = <TError = unknown | GetOauthGoogleCalendar401>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOauthGoogleCalendar>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOauthGoogleCalendarKey() : null);
  const swrFn = () => getOauthGoogleCalendar(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getOauthGoogleCallbackResponse302 = {
  data: unknown
  status: 302
}

export type getOauthGoogleCallbackResponse401 = {
  data: GetOauthGoogleCallback401
  status: 401
}
    
;
export type getOauthGoogleCallbackResponseError = (getOauthGoogleCallbackResponse302 | getOauthGoogleCallbackResponse401) & {
  headers: Headers;
};

export type getOauthGoogleCallbackResponse = (getOauthGoogleCallbackResponseError)

export const getGetOauthGoogleCallbackUrl = (params?: GetOauthGoogleCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/google/callback?${stringifiedParams}` : `/oauth/google/callback`
}

export const getOauthGoogleCallback = async (params?: GetOauthGoogleCallbackParams, options?: RequestInit): Promise<getOauthGoogleCallbackResponse> => {
  
  return customInstance<getOauthGoogleCallbackResponse>(getGetOauthGoogleCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetOauthGoogleCallbackKey = (params?: GetOauthGoogleCallbackParams,) => [`/oauth/google/callback`, ...(params ? [params]: [])] as const;

export type GetOauthGoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getOauthGoogleCallback>>>

export const useGetOauthGoogleCallback = <TError = unknown | GetOauthGoogleCallback401>(
  params?: GetOauthGoogleCallbackParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOauthGoogleCallback>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOauthGoogleCallbackKey(params) : null);
  const swrFn = () => getOauthGoogleCallback(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getGmailAccountsResponse200 = {
  data: GetGmailAccounts200Item[]
  status: 200
}

export type getGmailAccountsResponse401 = {
  data: GetGmailAccounts401
  status: 401
}

export type getGmailAccountsResponse500 = {
  data: GetGmailAccounts500
  status: 500
}
    
export type getGmailAccountsResponseSuccess = (getGmailAccountsResponse200) & {
  headers: Headers;
};
export type getGmailAccountsResponseError = (getGmailAccountsResponse401 | getGmailAccountsResponse500) & {
  headers: Headers;
};

export type getGmailAccountsResponse = (getGmailAccountsResponseSuccess | getGmailAccountsResponseError)

export const getGetGmailAccountsUrl = () => {


  

  return `/gmail/accounts`
}

export const getGmailAccounts = async ( options?: RequestInit): Promise<getGmailAccountsResponse> => {
  
  return customInstance<getGmailAccountsResponse>(getGetGmailAccountsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetGmailAccountsKey = () => [`/gmail/accounts`] as const;

export type GetGmailAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getGmailAccounts>>>

export const useGetGmailAccounts = <TError = GetGmailAccounts401 | GetGmailAccounts500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getGmailAccounts>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetGmailAccountsKey() : null);
  const swrFn = () => getGmailAccounts(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteGmailAccountsResponse200 = {
  data: DeleteGmailAccounts200
  status: 200
}

export type deleteGmailAccountsResponse401 = {
  data: DeleteGmailAccounts401
  status: 401
}

export type deleteGmailAccountsResponse404 = {
  data: DeleteGmailAccounts404
  status: 404
}

export type deleteGmailAccountsResponse500 = {
  data: DeleteGmailAccounts500
  status: 500
}
    
export type deleteGmailAccountsResponseSuccess = (deleteGmailAccountsResponse200) & {
  headers: Headers;
};
export type deleteGmailAccountsResponseError = (deleteGmailAccountsResponse401 | deleteGmailAccountsResponse404 | deleteGmailAccountsResponse500) & {
  headers: Headers;
};

export type deleteGmailAccountsResponse = (deleteGmailAccountsResponseSuccess | deleteGmailAccountsResponseError)

export const getDeleteGmailAccountsUrl = (params: DeleteGmailAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/gmail/accounts?${stringifiedParams}` : `/gmail/accounts`
}

export const deleteGmailAccounts = async (params: DeleteGmailAccountsParams, options?: RequestInit): Promise<deleteGmailAccountsResponse> => {
  
  return customInstance<deleteGmailAccountsResponse>(getDeleteGmailAccountsUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteGmailAccountsMutationFetcher = (params: DeleteGmailAccountsParams, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteGmailAccounts(params, options);
  }
}
export const getDeleteGmailAccountsMutationKey = (params: DeleteGmailAccountsParams,) => [`/gmail/accounts`, ...(params ? [params]: [])] as const;

export type DeleteGmailAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGmailAccounts>>>

export const useDeleteGmailAccounts = <TError = DeleteGmailAccounts401 | DeleteGmailAccounts404 | DeleteGmailAccounts500>(
  params: DeleteGmailAccountsParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteGmailAccounts>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteGmailAccounts>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteGmailAccountsMutationKey(params);
  const swrFn = getDeleteGmailAccountsMutationFetcher(params, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getGoogleCalendarAccountsResponse200 = {
  data: GetGoogleCalendarAccounts200Item[]
  status: 200
}

export type getGoogleCalendarAccountsResponse401 = {
  data: GetGoogleCalendarAccounts401
  status: 401
}

export type getGoogleCalendarAccountsResponse500 = {
  data: GetGoogleCalendarAccounts500
  status: 500
}
    
export type getGoogleCalendarAccountsResponseSuccess = (getGoogleCalendarAccountsResponse200) & {
  headers: Headers;
};
export type getGoogleCalendarAccountsResponseError = (getGoogleCalendarAccountsResponse401 | getGoogleCalendarAccountsResponse500) & {
  headers: Headers;
};

export type getGoogleCalendarAccountsResponse = (getGoogleCalendarAccountsResponseSuccess | getGoogleCalendarAccountsResponseError)

export const getGetGoogleCalendarAccountsUrl = () => {


  

  return `/google-calendar/accounts`
}

export const getGoogleCalendarAccounts = async ( options?: RequestInit): Promise<getGoogleCalendarAccountsResponse> => {
  
  return customInstance<getGoogleCalendarAccountsResponse>(getGetGoogleCalendarAccountsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetGoogleCalendarAccountsKey = () => [`/google-calendar/accounts`] as const;

export type GetGoogleCalendarAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getGoogleCalendarAccounts>>>

export const useGetGoogleCalendarAccounts = <TError = GetGoogleCalendarAccounts401 | GetGoogleCalendarAccounts500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getGoogleCalendarAccounts>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetGoogleCalendarAccountsKey() : null);
  const swrFn = () => getGoogleCalendarAccounts(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteGoogleCalendarAccountsResponse200 = {
  data: DeleteGoogleCalendarAccounts200
  status: 200
}

export type deleteGoogleCalendarAccountsResponse401 = {
  data: DeleteGoogleCalendarAccounts401
  status: 401
}

export type deleteGoogleCalendarAccountsResponse404 = {
  data: DeleteGoogleCalendarAccounts404
  status: 404
}

export type deleteGoogleCalendarAccountsResponse500 = {
  data: DeleteGoogleCalendarAccounts500
  status: 500
}
    
export type deleteGoogleCalendarAccountsResponseSuccess = (deleteGoogleCalendarAccountsResponse200) & {
  headers: Headers;
};
export type deleteGoogleCalendarAccountsResponseError = (deleteGoogleCalendarAccountsResponse401 | deleteGoogleCalendarAccountsResponse404 | deleteGoogleCalendarAccountsResponse500) & {
  headers: Headers;
};

export type deleteGoogleCalendarAccountsResponse = (deleteGoogleCalendarAccountsResponseSuccess | deleteGoogleCalendarAccountsResponseError)

export const getDeleteGoogleCalendarAccountsUrl = (params: DeleteGoogleCalendarAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/google-calendar/accounts?${stringifiedParams}` : `/google-calendar/accounts`
}

export const deleteGoogleCalendarAccounts = async (params: DeleteGoogleCalendarAccountsParams, options?: RequestInit): Promise<deleteGoogleCalendarAccountsResponse> => {
  
  return customInstance<deleteGoogleCalendarAccountsResponse>(getDeleteGoogleCalendarAccountsUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteGoogleCalendarAccountsMutationFetcher = (params: DeleteGoogleCalendarAccountsParams, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteGoogleCalendarAccounts(params, options);
  }
}
export const getDeleteGoogleCalendarAccountsMutationKey = (params: DeleteGoogleCalendarAccountsParams,) => [`/google-calendar/accounts`, ...(params ? [params]: [])] as const;

export type DeleteGoogleCalendarAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGoogleCalendarAccounts>>>

export const useDeleteGoogleCalendarAccounts = <TError = DeleteGoogleCalendarAccounts401 | DeleteGoogleCalendarAccounts404 | DeleteGoogleCalendarAccounts500>(
  params: DeleteGoogleCalendarAccountsParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteGoogleCalendarAccounts>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteGoogleCalendarAccounts>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteGoogleCalendarAccountsMutationKey(params);
  const swrFn = getDeleteGoogleCalendarAccountsMutationFetcher(params, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMessagesResponse200 = {
  data: GetMessages200
  status: 200
}

export type getMessagesResponse400 = {
  data: GetMessages400
  status: 400
}

export type getMessagesResponse401 = {
  data: GetMessages401
  status: 401
}

export type getMessagesResponse500 = {
  data: GetMessages500
  status: 500
}
    
export type getMessagesResponseSuccess = (getMessagesResponse200) & {
  headers: Headers;
};
export type getMessagesResponseError = (getMessagesResponse400 | getMessagesResponse401 | getMessagesResponse500) & {
  headers: Headers;
};

export type getMessagesResponse = (getMessagesResponseSuccess | getMessagesResponseError)

export const getGetMessagesUrl = (params: GetMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/messages?${stringifiedParams}` : `/messages`
}

export const getMessages = async (params: GetMessagesParams, options?: RequestInit): Promise<getMessagesResponse> => {
  
  return customInstance<getMessagesResponse>(getGetMessagesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetMessagesKey = (params: GetMessagesParams,) => [`/messages`, ...(params ? [params]: [])] as const;

export type GetMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getMessages>>>

export const useGetMessages = <TError = GetMessages400 | GetMessages401 | GetMessages500>(
  params: GetMessagesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMessages>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMessagesKey(params) : null);
  const swrFn = () => getMessages(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postChatResponse200 = {
  data: PostChat200
  status: 200
}

export type postChatResponse400 = {
  data: PostChat400
  status: 400
}

export type postChatResponse401 = {
  data: PostChat401
  status: 401
}

export type postChatResponse429 = {
  data: PostChat429
  status: 429
}
    
export type postChatResponseSuccess = (postChatResponse200) & {
  headers: Headers;
};
export type postChatResponseError = (postChatResponse400 | postChatResponse401 | postChatResponse429) & {
  headers: Headers;
};

export type postChatResponse = (postChatResponseSuccess | postChatResponseError)

export const getPostChatUrl = () => {


  

  return `/chat`
}

export const postChat = async (postChatBody: PostChatBody, options?: RequestInit): Promise<postChatResponse> => {
  
  return customInstance<postChatResponse>(getPostChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postChatBody,)
  }
);}




export const getPostChatMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostChatBody }) => {
    return postChat(arg, options);
  }
}
export const getPostChatMutationKey = () => [`/chat`] as const;

export type PostChatMutationResult = NonNullable<Awaited<ReturnType<typeof postChat>>>

export const usePostChat = <TError = PostChat400 | PostChat401 | PostChat429>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postChat>>, TError, Key, PostChatBody, Awaited<ReturnType<typeof postChat>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostChatMutationKey();
  const swrFn = getPostChatMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postChatStreamResponse200 = {
  data: unknown
  status: 200
}

export type postChatStreamResponse400 = {
  data: PostChatStream400
  status: 400
}

export type postChatStreamResponse401 = {
  data: PostChatStream401
  status: 401
}

export type postChatStreamResponse429 = {
  data: PostChatStream429
  status: 429
}
    
export type postChatStreamResponseSuccess = (postChatStreamResponse200) & {
  headers: Headers;
};
export type postChatStreamResponseError = (postChatStreamResponse400 | postChatStreamResponse401 | postChatStreamResponse429) & {
  headers: Headers;
};

export type postChatStreamResponse = (postChatStreamResponseSuccess | postChatStreamResponseError)

export const getPostChatStreamUrl = () => {


  

  return `/chat/stream`
}

export const postChatStream = async (postChatStreamBody: PostChatStreamBody, options?: RequestInit): Promise<postChatStreamResponse> => {
  
  return customInstance<postChatStreamResponse>(getPostChatStreamUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postChatStreamBody,)
  }
);}




export const getPostChatStreamMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostChatStreamBody }) => {
    return postChatStream(arg, options);
  }
}
export const getPostChatStreamMutationKey = () => [`/chat/stream`] as const;

export type PostChatStreamMutationResult = NonNullable<Awaited<ReturnType<typeof postChatStream>>>

export const usePostChatStream = <TError = PostChatStream400 | PostChatStream401 | PostChatStream429>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postChatStream>>, TError, Key, PostChatStreamBody, Awaited<ReturnType<typeof postChatStream>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostChatStreamMutationKey();
  const swrFn = getPostChatStreamMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getXAccountResponse200 = {
  data: GetXAccount200
  status: 200
}

export type getXAccountResponse401 = {
  data: GetXAccount401
  status: 401
}

export type getXAccountResponse404 = {
  data: GetXAccount404
  status: 404
}

export type getXAccountResponse500 = {
  data: GetXAccount500
  status: 500
}
    
export type getXAccountResponseSuccess = (getXAccountResponse200) & {
  headers: Headers;
};
export type getXAccountResponseError = (getXAccountResponse401 | getXAccountResponse404 | getXAccountResponse500) & {
  headers: Headers;
};

export type getXAccountResponse = (getXAccountResponseSuccess | getXAccountResponseError)

export const getGetXAccountUrl = () => {


  

  return `/x-account/`
}

export const getXAccount = async ( options?: RequestInit): Promise<getXAccountResponse> => {
  
  return customInstance<getXAccountResponse>(getGetXAccountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetXAccountKey = () => [`/x-account/`] as const;

export type GetXAccountQueryResult = NonNullable<Awaited<ReturnType<typeof getXAccount>>>

export const useGetXAccount = <TError = GetXAccount401 | GetXAccount404 | GetXAccount500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getXAccount>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetXAccountKey() : null);
  const swrFn = () => getXAccount(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postXAccountResponse200 = {
  data: PostXAccount200
  status: 200
}

export type postXAccountResponse401 = {
  data: PostXAccount401
  status: 401
}

export type postXAccountResponse500 = {
  data: PostXAccount500
  status: 500
}
    
export type postXAccountResponseSuccess = (postXAccountResponse200) & {
  headers: Headers;
};
export type postXAccountResponseError = (postXAccountResponse401 | postXAccountResponse500) & {
  headers: Headers;
};

export type postXAccountResponse = (postXAccountResponseSuccess | postXAccountResponseError)

export const getPostXAccountUrl = () => {


  

  return `/x-account/`
}

export const postXAccount = async (postXAccountBody: PostXAccountBody, options?: RequestInit): Promise<postXAccountResponse> => {
  
  return customInstance<postXAccountResponse>(getPostXAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXAccountBody,)
  }
);}




export const getPostXAccountMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostXAccountBody }) => {
    return postXAccount(arg, options);
  }
}
export const getPostXAccountMutationKey = () => [`/x-account/`] as const;

export type PostXAccountMutationResult = NonNullable<Awaited<ReturnType<typeof postXAccount>>>

export const usePostXAccount = <TError = PostXAccount401 | PostXAccount500>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postXAccount>>, TError, Key, PostXAccountBody, Awaited<ReturnType<typeof postXAccount>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostXAccountMutationKey();
  const swrFn = getPostXAccountMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteXAccountResponse200 = {
  data: DeleteXAccount200
  status: 200
}

export type deleteXAccountResponse401 = {
  data: DeleteXAccount401
  status: 401
}

export type deleteXAccountResponse404 = {
  data: DeleteXAccount404
  status: 404
}

export type deleteXAccountResponse500 = {
  data: DeleteXAccount500
  status: 500
}
    
export type deleteXAccountResponseSuccess = (deleteXAccountResponse200) & {
  headers: Headers;
};
export type deleteXAccountResponseError = (deleteXAccountResponse401 | deleteXAccountResponse404 | deleteXAccountResponse500) & {
  headers: Headers;
};

export type deleteXAccountResponse = (deleteXAccountResponseSuccess | deleteXAccountResponseError)

export const getDeleteXAccountUrl = () => {


  

  return `/x-account/`
}

export const deleteXAccount = async ( options?: RequestInit): Promise<deleteXAccountResponse> => {
  
  return customInstance<deleteXAccountResponse>(getDeleteXAccountUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteXAccountMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteXAccount(options);
  }
}
export const getDeleteXAccountMutationKey = () => [`/x-account/`] as const;

export type DeleteXAccountMutationResult = NonNullable<Awaited<ReturnType<typeof deleteXAccount>>>

export const useDeleteXAccount = <TError = DeleteXAccount401 | DeleteXAccount404 | DeleteXAccount500>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteXAccount>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteXAccount>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteXAccountMutationKey();
  const swrFn = getDeleteXAccountMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getTelegramResponse200 = {
  data: GetTelegram200
  status: 200
}

export type getTelegramResponse401 = {
  data: GetTelegram401
  status: 401
}

export type getTelegramResponse404 = {
  data: GetTelegram404
  status: 404
}

export type getTelegramResponse500 = {
  data: GetTelegram500
  status: 500
}
    
export type getTelegramResponseSuccess = (getTelegramResponse200) & {
  headers: Headers;
};
export type getTelegramResponseError = (getTelegramResponse401 | getTelegramResponse404 | getTelegramResponse500) & {
  headers: Headers;
};

export type getTelegramResponse = (getTelegramResponseSuccess | getTelegramResponseError)

export const getGetTelegramUrl = () => {


  

  return `/telegram/`
}

export const getTelegram = async ( options?: RequestInit): Promise<getTelegramResponse> => {
  
  return customInstance<getTelegramResponse>(getGetTelegramUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetTelegramKey = () => [`/telegram/`] as const;

export type GetTelegramQueryResult = NonNullable<Awaited<ReturnType<typeof getTelegram>>>

export const useGetTelegram = <TError = GetTelegram401 | GetTelegram404 | GetTelegram500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTelegram>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTelegramKey() : null);
  const swrFn = () => getTelegram(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postTelegramResponse200 = {
  data: PostTelegram200
  status: 200
}

export type postTelegramResponse400 = {
  data: PostTelegram400
  status: 400
}

export type postTelegramResponse401 = {
  data: PostTelegram401
  status: 401
}

export type postTelegramResponse500 = {
  data: PostTelegram500
  status: 500
}
    
export type postTelegramResponseSuccess = (postTelegramResponse200) & {
  headers: Headers;
};
export type postTelegramResponseError = (postTelegramResponse400 | postTelegramResponse401 | postTelegramResponse500) & {
  headers: Headers;
};

export type postTelegramResponse = (postTelegramResponseSuccess | postTelegramResponseError)

export const getPostTelegramUrl = () => {


  

  return `/telegram/`
}

export const postTelegram = async (postTelegramBody: PostTelegramBody, options?: RequestInit): Promise<postTelegramResponse> => {
  
  return customInstance<postTelegramResponse>(getPostTelegramUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postTelegramBody,)
  }
);}




export const getPostTelegramMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostTelegramBody }) => {
    return postTelegram(arg, options);
  }
}
export const getPostTelegramMutationKey = () => [`/telegram/`] as const;

export type PostTelegramMutationResult = NonNullable<Awaited<ReturnType<typeof postTelegram>>>

export const usePostTelegram = <TError = PostTelegram400 | PostTelegram401 | PostTelegram500>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postTelegram>>, TError, Key, PostTelegramBody, Awaited<ReturnType<typeof postTelegram>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostTelegramMutationKey();
  const swrFn = getPostTelegramMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteTelegramResponse200 = {
  data: DeleteTelegram200
  status: 200
}

export type deleteTelegramResponse401 = {
  data: DeleteTelegram401
  status: 401
}

export type deleteTelegramResponse404 = {
  data: DeleteTelegram404
  status: 404
}

export type deleteTelegramResponse500 = {
  data: DeleteTelegram500
  status: 500
}
    
export type deleteTelegramResponseSuccess = (deleteTelegramResponse200) & {
  headers: Headers;
};
export type deleteTelegramResponseError = (deleteTelegramResponse401 | deleteTelegramResponse404 | deleteTelegramResponse500) & {
  headers: Headers;
};

export type deleteTelegramResponse = (deleteTelegramResponseSuccess | deleteTelegramResponseError)

export const getDeleteTelegramUrl = () => {


  

  return `/telegram/`
}

export const deleteTelegram = async ( options?: RequestInit): Promise<deleteTelegramResponse> => {
  
  return customInstance<deleteTelegramResponse>(getDeleteTelegramUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteTelegramMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteTelegram(options);
  }
}
export const getDeleteTelegramMutationKey = () => [`/telegram/`] as const;

export type DeleteTelegramMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTelegram>>>

export const useDeleteTelegram = <TError = DeleteTelegram401 | DeleteTelegram404 | DeleteTelegram500>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteTelegram>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteTelegram>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteTelegramMutationKey();
  const swrFn = getDeleteTelegramMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
