/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetAuthStatus200,
  GetAuthStatus401,
  PostEmailChatBody,
  PostEmailCreateBody,
  PostXAccountBody,
  PostXChatBody,
  PostXCreateBody
} from '.././model';

import { customInstance } from '../../custom-client';

export type getAuthLoginResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLoginResponseSuccess = (getAuthLoginResponse200) & {
  headers: Headers;
};
;

export type getAuthLoginResponse = (getAuthLoginResponseSuccess)

export const getGetAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const getAuthLogin = async ( options?: RequestInit): Promise<getAuthLoginResponse> => {
  
  return customInstance<getAuthLoginResponse>(getGetAuthLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthCallbackResponse200 = {
  data: void
  status: 200
}
    
export type getAuthCallbackResponseSuccess = (getAuthCallbackResponse200) & {
  headers: Headers;
};
;

export type getAuthCallbackResponse = (getAuthCallbackResponseSuccess)

export const getGetAuthCallbackUrl = () => {


  

  return `/auth/callback`
}

export const getAuthCallback = async ( options?: RequestInit): Promise<getAuthCallbackResponse> => {
  
  return customInstance<getAuthCallbackResponse>(getGetAuthCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthStatusResponse200 = {
  data: GetAuthStatus200
  status: 200
}

export type getAuthStatusResponse401 = {
  data: GetAuthStatus401
  status: 401
}
    
export type getAuthStatusResponseSuccess = (getAuthStatusResponse200) & {
  headers: Headers;
};
export type getAuthStatusResponseError = (getAuthStatusResponse401) & {
  headers: Headers;
};

export type getAuthStatusResponse = (getAuthStatusResponseSuccess | getAuthStatusResponseError)

export const getGetAuthStatusUrl = () => {


  

  return `/auth/status`
}

export const getAuthStatus = async ( options?: RequestInit): Promise<getAuthStatusResponse> => {
  
  return customInstance<getAuthStatusResponse>(getGetAuthStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthLogoutResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLogoutResponseSuccess = (getAuthLogoutResponse200) & {
  headers: Headers;
};
;

export type getAuthLogoutResponse = (getAuthLogoutResponseSuccess)

export const getGetAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const getAuthLogout = async ( options?: RequestInit): Promise<getAuthLogoutResponse> => {
  
  return customInstance<getAuthLogoutResponse>(getGetAuthLogoutUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getAuthGoogleResponse200 = {
  data: void
  status: 200
}
    
export type getAuthGoogleResponseSuccess = (getAuthGoogleResponse200) & {
  headers: Headers;
};
;

export type getAuthGoogleResponse = (getAuthGoogleResponseSuccess)

export const getGetAuthGoogleUrl = () => {


  

  return `/auth/google`
}

export const getAuthGoogle = async ( options?: RequestInit): Promise<getAuthGoogleResponse> => {
  
  return customInstance<getAuthGoogleResponse>(getGetAuthGoogleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getOauthGoogleCallbackResponse200 = {
  data: void
  status: 200
}
    
export type getOauthGoogleCallbackResponseSuccess = (getOauthGoogleCallbackResponse200) & {
  headers: Headers;
};
;

export type getOauthGoogleCallbackResponse = (getOauthGoogleCallbackResponseSuccess)

export const getGetOauthGoogleCallbackUrl = () => {


  

  return `/oauth/google/callback`
}

export const getOauthGoogleCallback = async ( options?: RequestInit): Promise<getOauthGoogleCallbackResponse> => {
  
  return customInstance<getOauthGoogleCallbackResponse>(getGetOauthGoogleCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getXAccountResponse200 = {
  data: void
  status: 200
}
    
export type getXAccountResponseSuccess = (getXAccountResponse200) & {
  headers: Headers;
};
;

export type getXAccountResponse = (getXAccountResponseSuccess)

export const getGetXAccountUrl = () => {


  

  return `/x-account/`
}

export const getXAccount = async ( options?: RequestInit): Promise<getXAccountResponse> => {
  
  return customInstance<getXAccountResponse>(getGetXAccountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type postXAccountResponse200 = {
  data: void
  status: 200
}
    
export type postXAccountResponseSuccess = (postXAccountResponse200) & {
  headers: Headers;
};
;

export type postXAccountResponse = (postXAccountResponseSuccess)

export const getPostXAccountUrl = () => {


  

  return `/x-account/`
}

export const postXAccount = async (postXAccountBody: PostXAccountBody, options?: RequestInit): Promise<postXAccountResponse> => {
  
  return customInstance<postXAccountResponse>(getPostXAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXAccountBody,)
  }
);}


export type deleteXAccountResponse200 = {
  data: void
  status: 200
}
    
export type deleteXAccountResponseSuccess = (deleteXAccountResponse200) & {
  headers: Headers;
};
;

export type deleteXAccountResponse = (deleteXAccountResponseSuccess)

export const getDeleteXAccountUrl = () => {


  

  return `/x-account/`
}

export const deleteXAccount = async ( options?: RequestInit): Promise<deleteXAccountResponse> => {
  
  return customInstance<deleteXAccountResponse>(getDeleteXAccountUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


export type postEmailCreateResponse200 = {
  data: void
  status: 200
}
    
export type postEmailCreateResponseSuccess = (postEmailCreateResponse200) & {
  headers: Headers;
};
;

export type postEmailCreateResponse = (postEmailCreateResponseSuccess)

export const getPostEmailCreateUrl = () => {


  

  return `/email/create`
}

export const postEmailCreate = async (postEmailCreateBody: PostEmailCreateBody, options?: RequestInit): Promise<postEmailCreateResponse> => {
  
  return customInstance<postEmailCreateResponse>(getPostEmailCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postEmailCreateBody,)
  }
);}


export type postEmailChatResponse200 = {
  data: void
  status: 200
}
    
export type postEmailChatResponseSuccess = (postEmailChatResponse200) & {
  headers: Headers;
};
;

export type postEmailChatResponse = (postEmailChatResponseSuccess)

export const getPostEmailChatUrl = () => {


  

  return `/email/chat`
}

export const postEmailChat = async (postEmailChatBody: PostEmailChatBody, options?: RequestInit): Promise<postEmailChatResponse> => {
  
  return customInstance<postEmailChatResponse>(getPostEmailChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postEmailChatBody,)
  }
);}


export type postXCreateResponse200 = {
  data: void
  status: 200
}
    
export type postXCreateResponseSuccess = (postXCreateResponse200) & {
  headers: Headers;
};
;

export type postXCreateResponse = (postXCreateResponseSuccess)

export const getPostXCreateUrl = () => {


  

  return `/x/create`
}

export const postXCreate = async (postXCreateBody: PostXCreateBody, options?: RequestInit): Promise<postXCreateResponse> => {
  
  return customInstance<postXCreateResponse>(getPostXCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXCreateBody,)
  }
);}


export type postXChatResponse200 = {
  data: void
  status: 200
}
    
export type postXChatResponseSuccess = (postXChatResponse200) & {
  headers: Headers;
};
;

export type postXChatResponse = (postXChatResponseSuccess)

export const getPostXChatUrl = () => {


  

  return `/x/chat`
}

export const postXChat = async (postXChatBody: PostXChatBody, options?: RequestInit): Promise<postXChatResponse> => {
  
  return customInstance<postXChatResponse>(getPostXChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXChatBody,)
  }
);}


