/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  DeleteGmailAccounts200,
  DeleteGmailAccounts401,
  DeleteGmailAccounts404,
  DeleteGmailAccounts500,
  DeleteGmailAccountsParams,
  DeleteTelegram200,
  DeleteTelegram401,
  DeleteTelegram404,
  DeleteTelegram500,
  GetAuthGoogle401,
  GetAuthStatus200,
  GetAuthStatus401,
  GetGmailAccounts200Item,
  GetGmailAccounts401,
  GetGmailAccounts500,
  GetMessages200,
  GetMessages400,
  GetMessages401,
  GetMessages500,
  GetMessagesParams,
  GetOauthGoogleCallback401,
  GetOauthGoogleCallbackParams,
  GetTelegram200,
  GetTelegram401,
  GetTelegram404,
  GetTelegram500,
  PostChat200,
  PostChat400,
  PostChat401,
  PostChat429,
  PostChatBody,
  PostChatStream400,
  PostChatStream401,
  PostChatStream429,
  PostChatStreamBody,
  PostTelegram200,
  PostTelegram401,
  PostTelegram500,
  PostTelegramBody,
  PostXAccountBody
} from '../../api/models';

import { customInstance } from '../../custom-client';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
export type getAuthLoginResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLoginResponseSuccess = (getAuthLoginResponse200) & {
  headers: Headers;
};
;

export type getAuthLoginResponse = (getAuthLoginResponseSuccess)

export const getGetAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const getAuthLogin = async ( options?: RequestInit): Promise<getAuthLoginResponse> => {
  
  return customInstance<getAuthLoginResponse>(getGetAuthLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthLoginKey = () => [`/auth/login`] as const;

export type GetAuthLoginQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthLogin>>>

export const useGetAuthLogin = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthLogin>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthLoginKey() : null);
  const swrFn = () => getAuthLogin(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getAuthCallbackResponse200 = {
  data: void
  status: 200
}
    
export type getAuthCallbackResponseSuccess = (getAuthCallbackResponse200) & {
  headers: Headers;
};
;

export type getAuthCallbackResponse = (getAuthCallbackResponseSuccess)

export const getGetAuthCallbackUrl = () => {


  

  return `/auth/callback`
}

export const getAuthCallback = async ( options?: RequestInit): Promise<getAuthCallbackResponse> => {
  
  return customInstance<getAuthCallbackResponse>(getGetAuthCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthCallbackKey = () => [`/auth/callback`] as const;

export type GetAuthCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthCallback>>>

export const useGetAuthCallback = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthCallback>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthCallbackKey() : null);
  const swrFn = () => getAuthCallback(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getAuthStatusResponse200 = {
  data: GetAuthStatus200
  status: 200
}

export type getAuthStatusResponse401 = {
  data: GetAuthStatus401
  status: 401
}
    
export type getAuthStatusResponseSuccess = (getAuthStatusResponse200) & {
  headers: Headers;
};
export type getAuthStatusResponseError = (getAuthStatusResponse401) & {
  headers: Headers;
};

export type getAuthStatusResponse = (getAuthStatusResponseSuccess | getAuthStatusResponseError)

export const getGetAuthStatusUrl = () => {


  

  return `/auth/status`
}

export const getAuthStatus = async ( options?: RequestInit): Promise<getAuthStatusResponse> => {
  
  return customInstance<getAuthStatusResponse>(getGetAuthStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthStatusKey = () => [`/auth/status`] as const;

export type GetAuthStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthStatus>>>

export const useGetAuthStatus = <TError = GetAuthStatus401>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthStatus>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthStatusKey() : null);
  const swrFn = () => getAuthStatus(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getAuthLogoutResponse200 = {
  data: void
  status: 200
}
    
export type getAuthLogoutResponseSuccess = (getAuthLogoutResponse200) & {
  headers: Headers;
};
;

export type getAuthLogoutResponse = (getAuthLogoutResponseSuccess)

export const getGetAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const getAuthLogout = async ( options?: RequestInit): Promise<getAuthLogoutResponse> => {
  
  return customInstance<getAuthLogoutResponse>(getGetAuthLogoutUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthLogoutKey = () => [`/auth/logout`] as const;

export type GetAuthLogoutQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthLogout>>>

export const useGetAuthLogout = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthLogout>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthLogoutKey() : null);
  const swrFn = () => getAuthLogout(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getAuthGoogleResponse302 = {
  data: unknown
  status: 302
}

export type getAuthGoogleResponse401 = {
  data: GetAuthGoogle401
  status: 401
}
    
;
export type getAuthGoogleResponseError = (getAuthGoogleResponse302 | getAuthGoogleResponse401) & {
  headers: Headers;
};

export type getAuthGoogleResponse = (getAuthGoogleResponseError)

export const getGetAuthGoogleUrl = () => {


  

  return `/auth/google`
}

export const getAuthGoogle = async ( options?: RequestInit): Promise<getAuthGoogleResponse> => {
  
  return customInstance<getAuthGoogleResponse>(getGetAuthGoogleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetAuthGoogleKey = () => [`/auth/google`] as const;

export type GetAuthGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthGoogle>>>

export const useGetAuthGoogle = <TError = unknown | GetAuthGoogle401>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthGoogle>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthGoogleKey() : null);
  const swrFn = () => getAuthGoogle(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getOauthGoogleCallbackResponse302 = {
  data: unknown
  status: 302
}

export type getOauthGoogleCallbackResponse401 = {
  data: GetOauthGoogleCallback401
  status: 401
}
    
;
export type getOauthGoogleCallbackResponseError = (getOauthGoogleCallbackResponse302 | getOauthGoogleCallbackResponse401) & {
  headers: Headers;
};

export type getOauthGoogleCallbackResponse = (getOauthGoogleCallbackResponseError)

export const getGetOauthGoogleCallbackUrl = (params?: GetOauthGoogleCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/google/callback?${stringifiedParams}` : `/oauth/google/callback`
}

export const getOauthGoogleCallback = async (params?: GetOauthGoogleCallbackParams, options?: RequestInit): Promise<getOauthGoogleCallbackResponse> => {
  
  return customInstance<getOauthGoogleCallbackResponse>(getGetOauthGoogleCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetOauthGoogleCallbackKey = (params?: GetOauthGoogleCallbackParams,) => [`/oauth/google/callback`, ...(params ? [params]: [])] as const;

export type GetOauthGoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getOauthGoogleCallback>>>

export const useGetOauthGoogleCallback = <TError = unknown | GetOauthGoogleCallback401>(
  params?: GetOauthGoogleCallbackParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOauthGoogleCallback>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOauthGoogleCallbackKey(params) : null);
  const swrFn = () => getOauthGoogleCallback(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getGmailAccountsResponse200 = {
  data: GetGmailAccounts200Item[]
  status: 200
}

export type getGmailAccountsResponse401 = {
  data: GetGmailAccounts401
  status: 401
}

export type getGmailAccountsResponse500 = {
  data: GetGmailAccounts500
  status: 500
}
    
export type getGmailAccountsResponseSuccess = (getGmailAccountsResponse200) & {
  headers: Headers;
};
export type getGmailAccountsResponseError = (getGmailAccountsResponse401 | getGmailAccountsResponse500) & {
  headers: Headers;
};

export type getGmailAccountsResponse = (getGmailAccountsResponseSuccess | getGmailAccountsResponseError)

export const getGetGmailAccountsUrl = () => {


  

  return `/gmail-accounts`
}

export const getGmailAccounts = async ( options?: RequestInit): Promise<getGmailAccountsResponse> => {
  
  return customInstance<getGmailAccountsResponse>(getGetGmailAccountsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetGmailAccountsKey = () => [`/gmail-accounts`] as const;

export type GetGmailAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getGmailAccounts>>>

export const useGetGmailAccounts = <TError = GetGmailAccounts401 | GetGmailAccounts500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getGmailAccounts>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetGmailAccountsKey() : null);
  const swrFn = () => getGmailAccounts(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteGmailAccountsResponse200 = {
  data: DeleteGmailAccounts200
  status: 200
}

export type deleteGmailAccountsResponse401 = {
  data: DeleteGmailAccounts401
  status: 401
}

export type deleteGmailAccountsResponse404 = {
  data: DeleteGmailAccounts404
  status: 404
}

export type deleteGmailAccountsResponse500 = {
  data: DeleteGmailAccounts500
  status: 500
}
    
export type deleteGmailAccountsResponseSuccess = (deleteGmailAccountsResponse200) & {
  headers: Headers;
};
export type deleteGmailAccountsResponseError = (deleteGmailAccountsResponse401 | deleteGmailAccountsResponse404 | deleteGmailAccountsResponse500) & {
  headers: Headers;
};

export type deleteGmailAccountsResponse = (deleteGmailAccountsResponseSuccess | deleteGmailAccountsResponseError)

export const getDeleteGmailAccountsUrl = (params: DeleteGmailAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/gmail-accounts?${stringifiedParams}` : `/gmail-accounts`
}

export const deleteGmailAccounts = async (params: DeleteGmailAccountsParams, options?: RequestInit): Promise<deleteGmailAccountsResponse> => {
  
  return customInstance<deleteGmailAccountsResponse>(getDeleteGmailAccountsUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteGmailAccountsMutationFetcher = (params: DeleteGmailAccountsParams, options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteGmailAccounts(params, options);
  }
}
export const getDeleteGmailAccountsMutationKey = (params: DeleteGmailAccountsParams,) => [`/gmail-accounts`, ...(params ? [params]: [])] as const;

export type DeleteGmailAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGmailAccounts>>>

export const useDeleteGmailAccounts = <TError = DeleteGmailAccounts401 | DeleteGmailAccounts404 | DeleteGmailAccounts500>(
  params: DeleteGmailAccountsParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteGmailAccounts>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteGmailAccounts>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteGmailAccountsMutationKey(params);
  const swrFn = getDeleteGmailAccountsMutationFetcher(params, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMessagesResponse200 = {
  data: GetMessages200
  status: 200
}

export type getMessagesResponse400 = {
  data: GetMessages400
  status: 400
}

export type getMessagesResponse401 = {
  data: GetMessages401
  status: 401
}

export type getMessagesResponse500 = {
  data: GetMessages500
  status: 500
}
    
export type getMessagesResponseSuccess = (getMessagesResponse200) & {
  headers: Headers;
};
export type getMessagesResponseError = (getMessagesResponse400 | getMessagesResponse401 | getMessagesResponse500) & {
  headers: Headers;
};

export type getMessagesResponse = (getMessagesResponseSuccess | getMessagesResponseError)

export const getGetMessagesUrl = (params: GetMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/messages?${stringifiedParams}` : `/messages`
}

export const getMessages = async (params: GetMessagesParams, options?: RequestInit): Promise<getMessagesResponse> => {
  
  return customInstance<getMessagesResponse>(getGetMessagesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetMessagesKey = (params: GetMessagesParams,) => [`/messages`, ...(params ? [params]: [])] as const;

export type GetMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getMessages>>>

export const useGetMessages = <TError = GetMessages400 | GetMessages401 | GetMessages500>(
  params: GetMessagesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMessages>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMessagesKey(params) : null);
  const swrFn = () => getMessages(params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postChatResponse200 = {
  data: PostChat200
  status: 200
}

export type postChatResponse400 = {
  data: PostChat400
  status: 400
}

export type postChatResponse401 = {
  data: PostChat401
  status: 401
}

export type postChatResponse429 = {
  data: PostChat429
  status: 429
}
    
export type postChatResponseSuccess = (postChatResponse200) & {
  headers: Headers;
};
export type postChatResponseError = (postChatResponse400 | postChatResponse401 | postChatResponse429) & {
  headers: Headers;
};

export type postChatResponse = (postChatResponseSuccess | postChatResponseError)

export const getPostChatUrl = () => {


  

  return `/chat`
}

export const postChat = async (postChatBody: PostChatBody, options?: RequestInit): Promise<postChatResponse> => {
  
  return customInstance<postChatResponse>(getPostChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postChatBody,)
  }
);}




export const getPostChatMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostChatBody }) => {
    return postChat(arg, options);
  }
}
export const getPostChatMutationKey = () => [`/chat`] as const;

export type PostChatMutationResult = NonNullable<Awaited<ReturnType<typeof postChat>>>

export const usePostChat = <TError = PostChat400 | PostChat401 | PostChat429>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postChat>>, TError, Key, PostChatBody, Awaited<ReturnType<typeof postChat>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostChatMutationKey();
  const swrFn = getPostChatMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postChatStreamResponse200 = {
  data: unknown
  status: 200
}

export type postChatStreamResponse400 = {
  data: PostChatStream400
  status: 400
}

export type postChatStreamResponse401 = {
  data: PostChatStream401
  status: 401
}

export type postChatStreamResponse429 = {
  data: PostChatStream429
  status: 429
}
    
export type postChatStreamResponseSuccess = (postChatStreamResponse200) & {
  headers: Headers;
};
export type postChatStreamResponseError = (postChatStreamResponse400 | postChatStreamResponse401 | postChatStreamResponse429) & {
  headers: Headers;
};

export type postChatStreamResponse = (postChatStreamResponseSuccess | postChatStreamResponseError)

export const getPostChatStreamUrl = () => {


  

  return `/chat/stream`
}

export const postChatStream = async (postChatStreamBody: PostChatStreamBody, options?: RequestInit): Promise<postChatStreamResponse> => {
  
  return customInstance<postChatStreamResponse>(getPostChatStreamUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postChatStreamBody,)
  }
);}




export const getPostChatStreamMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostChatStreamBody }) => {
    return postChatStream(arg, options);
  }
}
export const getPostChatStreamMutationKey = () => [`/chat/stream`] as const;

export type PostChatStreamMutationResult = NonNullable<Awaited<ReturnType<typeof postChatStream>>>

export const usePostChatStream = <TError = PostChatStream400 | PostChatStream401 | PostChatStream429>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postChatStream>>, TError, Key, PostChatStreamBody, Awaited<ReturnType<typeof postChatStream>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostChatStreamMutationKey();
  const swrFn = getPostChatStreamMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getXAccountResponse200 = {
  data: void
  status: 200
}
    
export type getXAccountResponseSuccess = (getXAccountResponse200) & {
  headers: Headers;
};
;

export type getXAccountResponse = (getXAccountResponseSuccess)

export const getGetXAccountUrl = () => {


  

  return `/x-account/`
}

export const getXAccount = async ( options?: RequestInit): Promise<getXAccountResponse> => {
  
  return customInstance<getXAccountResponse>(getGetXAccountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetXAccountKey = () => [`/x-account/`] as const;

export type GetXAccountQueryResult = NonNullable<Awaited<ReturnType<typeof getXAccount>>>

export const useGetXAccount = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getXAccount>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetXAccountKey() : null);
  const swrFn = () => getXAccount(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postXAccountResponse200 = {
  data: void
  status: 200
}
    
export type postXAccountResponseSuccess = (postXAccountResponse200) & {
  headers: Headers;
};
;

export type postXAccountResponse = (postXAccountResponseSuccess)

export const getPostXAccountUrl = () => {


  

  return `/x-account/`
}

export const postXAccount = async (postXAccountBody: PostXAccountBody, options?: RequestInit): Promise<postXAccountResponse> => {
  
  return customInstance<postXAccountResponse>(getPostXAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postXAccountBody,)
  }
);}




export const getPostXAccountMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostXAccountBody }) => {
    return postXAccount(arg, options);
  }
}
export const getPostXAccountMutationKey = () => [`/x-account/`] as const;

export type PostXAccountMutationResult = NonNullable<Awaited<ReturnType<typeof postXAccount>>>

export const usePostXAccount = <TError = unknown>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postXAccount>>, TError, Key, PostXAccountBody, Awaited<ReturnType<typeof postXAccount>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostXAccountMutationKey();
  const swrFn = getPostXAccountMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteXAccountResponse200 = {
  data: void
  status: 200
}
    
export type deleteXAccountResponseSuccess = (deleteXAccountResponse200) & {
  headers: Headers;
};
;

export type deleteXAccountResponse = (deleteXAccountResponseSuccess)

export const getDeleteXAccountUrl = () => {


  

  return `/x-account/`
}

export const deleteXAccount = async ( options?: RequestInit): Promise<deleteXAccountResponse> => {
  
  return customInstance<deleteXAccountResponse>(getDeleteXAccountUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteXAccountMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteXAccount(options);
  }
}
export const getDeleteXAccountMutationKey = () => [`/x-account/`] as const;

export type DeleteXAccountMutationResult = NonNullable<Awaited<ReturnType<typeof deleteXAccount>>>

export const useDeleteXAccount = <TError = unknown>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteXAccount>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteXAccount>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteXAccountMutationKey();
  const swrFn = getDeleteXAccountMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getTelegramResponse200 = {
  data: GetTelegram200
  status: 200
}

export type getTelegramResponse401 = {
  data: GetTelegram401
  status: 401
}

export type getTelegramResponse404 = {
  data: GetTelegram404
  status: 404
}

export type getTelegramResponse500 = {
  data: GetTelegram500
  status: 500
}
    
export type getTelegramResponseSuccess = (getTelegramResponse200) & {
  headers: Headers;
};
export type getTelegramResponseError = (getTelegramResponse401 | getTelegramResponse404 | getTelegramResponse500) & {
  headers: Headers;
};

export type getTelegramResponse = (getTelegramResponseSuccess | getTelegramResponseError)

export const getGetTelegramUrl = () => {


  

  return `/telegram/`
}

export const getTelegram = async ( options?: RequestInit): Promise<getTelegramResponse> => {
  
  return customInstance<getTelegramResponse>(getGetTelegramUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getGetTelegramKey = () => [`/telegram/`] as const;

export type GetTelegramQueryResult = NonNullable<Awaited<ReturnType<typeof getTelegram>>>

export const useGetTelegram = <TError = GetTelegram401 | GetTelegram404 | GetTelegram500>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTelegram>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTelegramKey() : null);
  const swrFn = () => getTelegram(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postTelegramResponse200 = {
  data: PostTelegram200
  status: 200
}

export type postTelegramResponse401 = {
  data: PostTelegram401
  status: 401
}

export type postTelegramResponse500 = {
  data: PostTelegram500
  status: 500
}
    
export type postTelegramResponseSuccess = (postTelegramResponse200) & {
  headers: Headers;
};
export type postTelegramResponseError = (postTelegramResponse401 | postTelegramResponse500) & {
  headers: Headers;
};

export type postTelegramResponse = (postTelegramResponseSuccess | postTelegramResponseError)

export const getPostTelegramUrl = () => {


  

  return `/telegram/`
}

export const postTelegram = async (postTelegramBody: PostTelegramBody, options?: RequestInit): Promise<postTelegramResponse> => {
  
  return customInstance<postTelegramResponse>(getPostTelegramUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postTelegramBody,)
  }
);}




export const getPostTelegramMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, { arg }: { arg: PostTelegramBody }) => {
    return postTelegram(arg, options);
  }
}
export const getPostTelegramMutationKey = () => [`/telegram/`] as const;

export type PostTelegramMutationResult = NonNullable<Awaited<ReturnType<typeof postTelegram>>>

export const usePostTelegram = <TError = PostTelegram401 | PostTelegram500>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postTelegram>>, TError, Key, PostTelegramBody, Awaited<ReturnType<typeof postTelegram>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostTelegramMutationKey();
  const swrFn = getPostTelegramMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type deleteTelegramResponse200 = {
  data: DeleteTelegram200
  status: 200
}

export type deleteTelegramResponse401 = {
  data: DeleteTelegram401
  status: 401
}

export type deleteTelegramResponse404 = {
  data: DeleteTelegram404
  status: 404
}

export type deleteTelegramResponse500 = {
  data: DeleteTelegram500
  status: 500
}
    
export type deleteTelegramResponseSuccess = (deleteTelegramResponse200) & {
  headers: Headers;
};
export type deleteTelegramResponseError = (deleteTelegramResponse401 | deleteTelegramResponse404 | deleteTelegramResponse500) & {
  headers: Headers;
};

export type deleteTelegramResponse = (deleteTelegramResponseSuccess | deleteTelegramResponseError)

export const getDeleteTelegramUrl = () => {


  

  return `/telegram/`
}

export const deleteTelegram = async ( options?: RequestInit): Promise<deleteTelegramResponse> => {
  
  return customInstance<deleteTelegramResponse>(getDeleteTelegramUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteTelegramMutationFetcher = ( options?: SecondParameter<typeof customInstance>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteTelegram(options);
  }
}
export const getDeleteTelegramMutationKey = () => [`/telegram/`] as const;

export type DeleteTelegramMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTelegram>>>

export const useDeleteTelegram = <TError = DeleteTelegram401 | DeleteTelegram404 | DeleteTelegram500>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteTelegram>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteTelegram>>> & { swrKey?: string }, request?: SecondParameter<typeof customInstance>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteTelegramMutationKey();
  const swrFn = getDeleteTelegramMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
